### ISSUE TITLE
Error in ModSurfaceRules

### ISSUE THREAD

**Issue by Pierconic** [NerdyPuzzle/End-biomes-plugin-MCreator#2]
Attempting to compile a workspace with a regular biome and an end biome results in a syntax error in the ModSurfaceRules.JSON file. The error itself is as follows:
`[C:\Users\prcri\MCreatorWorkspaces\superiorstructuresrebirth\src\main\java\net\mcreator\superiorstructures\init\SuperiorstructuresModSurfaceRules.java:43](file:///C:/Users/prcri/MCreatorWorkspaces/superiorstructuresrebirth/src/main/java/net/mcreator/superiorstructures/init/SuperiorstructuresModSurfaceRules.java:43): error: ')' expected 
         noiseGeneratorSettings.surfaceRule()));`

and this is the specific section it refers to:
`public static void registerSurfaceRules(ResourceLocation biome, NoiseGeneratorSettings noiseGeneratorSettings, BlockState groundBlock, BlockState undergroundBlock) {
		((NoiseGeneratorSettingsAccess)(Object)noiseGeneratorSettings).addSurfaceRule(SurfaceRules.sequence(
		SurfaceRules.ifTrue(SurfaceRules.isBiome(ResourceKey.create(Registries.BIOME, biome)),
			SurfaceRules.sequence(
				SurfaceRules.ifTrue(SurfaceRules.ON_FLOOR, SurfaceRules.state(groundBlock)),
				SurfaceRules.ifTrue(SurfaceRules.UNDER_FLOOR, SurfaceRules.state(undergroundBlock)
				)
			),
			noiseGeneratorSettings.surfaceRule()));
	}`

The file isn't locked when the workspace's core files are locked, so any changes to this file reset whenever the workspace is compiled.

I am using MCreator 2023.4.52316, with the Forge 1.20.1 Generator, and version 2.3 of the plugin. (end_biome_8.) This issue persists when there are only two mod elements, and only the end biomes and Forge mixins plugins installed.

**Comment by NerdyPuzzle** [comment]
Thank you
