### ISSUE TITLE
Biome element missing

### ISSUE THREAD

**Issue by EndWayfarer** [NerdyPuzzle/End-biomes-plugin-MCreator#4]
I'm working in mcreator 2023.4, for 1.20.1, and I have the forge mixins. Most things are working, but when I was creating a new biome, there were no options to choose for the biome element, it's just a blank dropdown. And I can't create the biome without it.
![2024-06-14_20-38-12](https://github.com/NerdyPuzzle/End-biomes-plugin-MCreator/assets/172868595/919f257e-d1d0-464b-8926-daddacee59a0)
![2024-06-14_20-38-53](https://github.com/NerdyPuzzle/End-biomes-plugin-MCreator/assets/172868595/1224e22d-e67e-414e-bd93-9c49247f4798)

**Comment by NerdyPuzzle** [comment]
You need to create a normal biome first.
