### ISSUE TITLE
plugin is missing supported version

### ISSUE THREAD

**Issue by FuryTheFurious** [NerdyPuzzle/End-biomes-plugin-MCreator#7]
I am running the latest release on the supported version, 2024.1. 
upon restarting, i get the error 'plugin is missing supported version'
![Capture](https://github.com/user-attachments/assets/ddab65af-6e3a-449e-9c90-2781fc4eeef7)

**Comment by NerdyPuzzle** [comment]
You still have an outdated version present in your plugins folder. Delete it.

**Comment by FuryTheFurious** [comment]
there is a single plugin in my plugin folder, and it is the one labelled 2024.1, the version i was running.

**Comment by NerdyPuzzle** [comment]
You have one in the path where the universal plugin folder that all mcreator versions load is. You can see the full path in the error message.

**Comment by FuryTheFurious** [comment]
I only ever downloaded one plugin, and it was the for 2024.1. i have removed that plugin already and when i added it again, i still got the correct error. i am running on the supported version and i have never downloaded the unsupported version.

**Comment by NerdyPuzzle** [comment]
Well clearly you have done something wrong because supportedversions does exist. ![Screenshot_2024-07-16-22-22-28-90_87c2225eebc34d2513fa0e7ad5b93cfc.jpg](https://github.com/user-attachments/assets/1e150331-225d-44fa-8dda-e430b5e1d82c)
